name: CMake shared librarys

on:
  workflow_call:
    outputs:
      artifact-id:
        value: ${{ jobs.build.outputs.artifact-id }}
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
    - name: Install tooling
      run: |
           sudo apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends cmake gfortran gfortran-mingw-w64-x86-64
    - uses: actions/checkout@v4
    
    - name: Configure Linux shared library
      run: |
        mkdir build_linux
        cd build_linux
        cmake ..

    - name: Build Linux shared library
      run: |
           cd build_linux
           cmake --build . --target "shared"

    - name: Configure Windows shared library
      run: |
        mkdir build_win
        cd build_win
        cmake -DCMAKE_TOOLCHAIN_FILE=../TC-mingw.cmake ..

    - name: Build Windows shared library
      run: |
           cd build_win
           cmake --build . --target "shared"

    - name: Pack artifacts
      run: |
        mkdir shared_libs
        mv build_linux/mulitobj.so shared_libs
        mv build_win/multiobj.dll shared_libs
        tar -czvf shared_libs.tar.gz -C shared_libs
    - name: Upload artifacts
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        retention-days: 1
        path: shared_libs.tar.gz
