name: CMake shared librarys

on:
  workflow_call:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install tooling
      run: |
           sudo apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends cmake gfortran gfortran-mingw-w64-x86-64
    - uses: actions/checkout@v4
    
    - name: Configure Linux shared library
      run: |
        mkdir build_linux
        cd build_linux
        cmake ..

    - name: Build Linux shared library
      run: |
           cd build_linux
           cmake --build . --target "shared"

    - name: Configure Windows shared library
      run: |
        mkdir build_win
        cd build_win
        cmake -DCMAKE_TOOLCHAIN_FILE=../TC-mingw.cmake ..

    - name: Build Windows shared library
      run: |
           cd build_win
           cmake --build . --target "shared"

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          build_linux/multiobj.so
          build_win/multiobj.dll
