name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    uses: ./.github/workflows/build_libs.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build_linux/multiobj.so,build_win/multiobj.dll"
