name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    uses: ./.github/workflows/build_libs.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # we cannot yet download artifacts by id, see https://github.com/actions/download-artifact/issues/349
      # I took the below snippet from the comments in that issue report.
      - run: npm install @actions/artifact@2.1.9
      - name: download-build-artifact
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build.outputs.artifact-id }}
          ARTIFACTS_FOLDER: ./build
        with:
          script: |
            const {default: artifactClient} = require('@actions/artifact')
            const { ARTIFACT_ID, ARTIFACTS_FOLDER } = process.env
            await artifactClient.downloadArtifact(ARTIFACT_ID, { path: ARTIFACTS_FOLDER })
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build_linux/multiobj.so,build_win/multiobj.dll"
